services:
  # O serviço do n8n exposto na porta 5678
  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - '5678:5678'
    volumes:
      - n8n_data:/home/node/.n8n
      - ~/docker_shared:/home/shared
    networks:
      - mainnet
    env_file:
      - .env
    expose:
      - 5678
    restart: always

  # Servidor de tratamento com Python, exposto na porta 8000. Realiza o Build no arquivo Dockerfile
  fastapi:
    build: .
    ports:
      - 8000:8000
    volumes:
      - downloads:/app/downloads
    networks:
      - mainnet
    env_file:
      - .env
    expose:
      - 8000
    depends_on: 
      - n8n

  # Interface streamlit
  streamlit:
    build: 
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - 8501:8501
    volumes:
      - downloads:/app/downloads
    networks:
      - mainnet
    env_file:
      - .env
    expose: 
      - 8501
    depends_on: 
      - fastapi

volumes:
  n8n_data:
  downloads:

networks:
  mainnet:
    driver: bridge
