services:
  # Banco de dados MySQL para o n8n
  mysql:
    image: bitnami/mysql:9.3.0
    restart: always
    ports:
      - '3306:3306'
    networks:
      - mainnet
    env_file:
      - .env
    expose:
      - 3306

  # O serviço do n8n exposto na porta 5678
  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports:
      - '5678:5678'
    volumes:
      - n8n_data:/home/node/.n8n
      - ~/docker_shared:/home/shared
    networks:
      - mainnet
    env_file:
      - .env
    expose:
      - 5678
    restart: always

  # Servidor de tratamento com Python, exposto na porta 8000. Realiza o Build no arquivo Dockerfile
  fastapi:
    build: .
    networks:
      - mainnet
    env_file:
      - .env
    expose:
      - 8000
    depends_on: 
      - n8n
  
volumes:
  n8n_data:

networks:
  mainnet:
    driver: bridge
